<?php
/**
 * @file
 * Code for the GSB Feature Links FPP feature.
 */

include_once 'gsb_feature_links_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_links_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['links'] = array(
    'label' => t('Links'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/links',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

function gsb_feature_links_fpp_preprocess_fieldable_panels_pane (&$variables) {
  if ($vars['elements']['#bundle'] == 'links') {
    $wrapper = entity_metadata_wrapper($vars['elements']['#entity_type'], $vars['elements']['#element']);
    // Determine the Links style and set corresponding style class for pane.
    $vars['classes_array'][] = $wrapper->field_link_style->value();
  }
}
