<?php
/**
 * @file
 * Code for the GSB Feature Links FPP feature.
 */

include_once 'gsb_feature_links_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_links_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['links'] = array(
    'label' => t('Links'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/links',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
/**
 * Implements template_preprocess_fieldable_panels_pane()
 */
function gsb_feature_links_fpp_preprocess_fieldable_panels_pane (&$variables) {
  if ($variables['elements']['#bundle'] == 'links') {
    $wrapper = entity_metadata_wrapper($variables['elements']['#entity_type'], $variables['elements']['#element']);
    // Determine the Links style and set corresponding style class for pane.
    $variables['classes_array'][] = $wrapper->field_link_style->value();
  }
}

/**
 * Implements hook_ds_pre_render_alter()
 * 
 * For a links fpp - 
 * Remove the show-more-less classes for the fielditems ds group, if field_link_display_show_more 
 * is not set to true. 
 */
function gsb_feature_links_fpp_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {
  if ($layout_render_array['ds_content'][0]['#bundle'] == 'links') {
    if ($layout_render_array['ds_content'][1]['#id'] == 'fieldable_panels_pane_links_full_group_show_more') {
      $language = $context['entity']->language;
      if ($context['entity']->field_link_display_show_more[$language][0]['value'] != 1) {
        $layout_render_array['ds_content'][1]['#prefix'] = str_replace('show-more-less show-more-less-num-4 show-more-less-min-6 ', '', $layout_render_array['ds_content'][1]['#prefix']);
      }
    }
  }
}
